### ISSUE TITLE
Class variable feedbackWrapped not initialized

### ISSUE THREAD

**Issue by Virtex6** [nicholastmosher/PID#2]
feedbackWrapped is not initialized within constructor

**Comment by nicholastmosher** [comment]
Hi @Virtex6, can you tell me a little bit about your setup? Do you have a snippet of code that shows how you are trying to use this, or a compiler error message? 

(Also, just as a word of warning, this isn't meant for any kind of serious use, I only ever used it with toy arduino projects, but if you're doing something similar it might work well enough for you :)

**Comment by Virtex6** [comment]
I'm using it on an ESP32. I was wondering why i got a very high error value. This was a result that the memory behind the variable feedbackWrapped was not initialized with a default value => so there was an non zero value in it, which changes the behavior of the tick() function a lot and as a result there was a complete wrong error calculation. 

If I call setFeedbackWrapped(false) everything work as expected, but in my opinion this should be done in the constructor.

**Comment by nicholastmosher** [comment]
Ah I see. I just pushed a change that initializes `feedbackWrapped`, does that work for you? I didn't try building it because I don't have a build script in the repo and I forgot how I used to build this (probably importing it directly in an arduino project). Can you let me know if it works as expected?

**Comment by nicholastmosher** [comment]
Going to close this as fixed by https://github.com/nicholastmosher/PID/commit/f13095ace615a40e1eced65953f6d6e57bdc83f1
