### ISSUE TITLE
cycleIntegral formula interpretation clarification and discrepancy between wikipedia implementation

### ISSUE THREAD

**Issue by Dzitu** [nicholastmosher/PID#3]
In cpp/PID.cpp:185 there is:

`
int cycleIntegral = (lastError + error / 2) * deltaTime;
`
`
integralCumulation += cycleIntegral;
`

Based on PID article on wikipedia:

`integral := integral + error × dt`

I wonder if cycleIntegral was meant to be:
1. as it is (then I do not understand - please explain),
2. `int cycleIntegral = ((lastError + error) / 2) * deltaTime;` (in between last and current error),
3. `int cycleIntegral = error * deltaTime;` (as wikipedia suggests).

How do you see it?

**Comment by nicholastmosher** [comment]
Thanks for this and thanks for the PR to fix it! I apologize for being unresponsive for this, it was a high school project that I'd stopped paying attention to.

I'm going to close this since I believe it was resolved by #4. Thanks!
